### PR TITLE
Support for Kerala data

### LINKED ISSUE #4: Support for Kerala data
Integrate data from Kerala dashboard

### PR DESCRIPTION
**Pull request by manikandanj**
**Description of PR**
Added support for data from Kerala dashboard. Using response from endpoint https://dashboard.kerala.gov.in/maps/outside.geojson. 

_Note :_ The dashboard expects a cookie session id to be sent with the request. Have hardcoded it in the code. Doesn't seem to have an expiration based on testing so far. Need to add a workaround if we find out that it does expire after some time.  

Fixes #4

### CODE REVIEW

**Review by bee-rickey — COMMENTED** [review]
See if you can get the cookie from a dummy request to https://dashboard.kerala.gov.in/index.php ? The response header has the cookie I believe. Tried it here a long time back: https://github.com/bee-rickey/webScraper/blob/8f2330bccf211f104054ae90ca630362d583830b/extract.py#L13

**Comment by manikandanj** [comment]
@bee-rickey I got the cookie by sending a dummy request to above URL and hard-coding the same. You mean getting it dynamically for each request so there is no risk of it being expired?

**Comment by bee-rickey** [comment]
@manikandanj Yep. So it doesn't fail randomly. I remember it failing on postman without a request first being sent to get the cookie. Maybe they removed the expiry on cookie... Either ways, if it's not a lot of change, try getting it dynamically?

**Comment by manikandanj** [comment]
@bee-rickey Made the changes to getting the session id dynamically and set it in the request cookie.

**Pull request merged**
